Create a stylecheck for json
symcon/action-style pull request #1
Opened 2021-11-17 15:16 UTC by Sunnyka98

2021-11-24 15:31 UTC, paresy requested changes
Erstmal -> Cool, dass es funktioniert. Jetzt müssen wir es noch ein wenig schön machen. Anbei die Kommentare. Und bitte den Style fixen. Der müsste nämlich auch noch nicht stimmen.

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +    $dir= ".";
Warum definiert, wenn es nur einmal verwendet wird?

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +    $falseFiles = "";
stylecheck sollte ohne diesen Parameter auskommen :-)

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +    $exitcode = 0;
So funktionieren exitcodes nicht ;)

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +    $falseFiles =stylecheck($dir, $falseFiles);
Bitte camelCase und ich würde $invalidFiles bevorzugen. Außerdem hätte ich gerne in der Variable ein Array der Dateien/Pfade, welche falsch sind, damit man damit besser weiterarbeiten kann.

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +        $exitcode = 1;
Such mal nach PHP und Exit-Code

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +    echo "\n"."FALSEFILES"."\n";
Warum ein \n direkt am Anfang?

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +                    //Ignore the stubs
Wofür ist dies? Wenn nicht benötigt, bitte entfernen

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +    function checking(String $dir)
Ich finde `checking` einen sehr schwachen Funktionsnamen. checkPath wäre z.B. besser. Oder checkFilesInPath

2021-11-24 15:31 UTC, paresy commented on check-style-json.php
> +            echo "Files are equal";
Wir sind nur an den problematischen Dateien interessiert. Die "Guten" sind hoffentlich in der Überzahlt uns würden somit die Ausgabe unnötig überschwemmen

2021-11-24 16:03 UTC, Sunnyka98 commented on check-style-json.php
> +    $falseFiles = "";
Wenn ich die Zeile lösche gibt php den Fehler: "Undefined variable $falseFiles" aus.

2022-01-04 14:33 UTC, paresy approved these changes

2022-01-04 14:33 UTC, paresy commented
Ich habe die Datei jetzt hier hinzugefügt, da ich den Check dort besser platziert fand: https://github.com/symcon/StylePHP/blob/master/json-check.php

2022-01-04 14:33 UTC, closed without merging